name: aicycle_insurance
description: Flutter plugin to add AICycle Insurance Widget inside your project.
version: 0.0.3
homepage: https://github.com/Aicycle-Insurance/aicycle_insurance_plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_painter: ^1.0.1
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.0
  get: ^4.6.1
  image_picker: ^0.8.4
  http: ^0.13.3
  mime: ^1.0.2
  photo_view: ^0.13.0
  path_provider: ^2.0.4
  flutter_image_compress: ^1.1.0
  camerawesome: ^0.3.0
  path: ^1.8.0
  flutter_phosphor_icons: ^0.0.1+6
  image: ^3.0.1
  nanoid: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_gen_runner: ^3.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# Flutter gen
flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  assets:
    - assets/images/
    - assets/icons/
