name: aicycle_insurance
description: Flutter plugin to add AICycle Insurance Widget inside your project.
version: 0.0.2
homepage: https://github.com/Aicycle-Insurance/aicycle_insurance_plugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_painter: ^0.0.1
  cached_network_image: ^2.4.1
  flutter_svg: ^0.18.1
  get: ^3.26.0
  image_picker: ^0.6.7+22
  http: ^0.12.2
  mime: ^0.9.7
  photo_view: ^0.10.3
  path_provider: ^1.6.28
  flutter_image_compress: ^0.7.0
  camerawesome: ^0.2.2
  path: ^1.7.0

dev_dependencies:
  build_runner: ^1.11.0
  flutter_gen_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# Flutter gen
flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  assets:
    - assets/images/
    - assets/icons/
