name: aicycle_insurance
description: Flutter plugin to add AICycle Insurance Widget inside your project.
version: 0.0.3
homepage: https://github.com/Aicycle-Insurance/aicycle_insurance_plugin

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.5.1
  flutter_svg: ^0.18.1
  get: ^3.26.0
  image_picker: ^0.6.7+22
  http: ^0.12.2
  mime: ^0.9.7
  photo_view: ^0.10.3
  path_provider: ^1.6.28
  flutter_image_compress: ^0.7.0
  camerawesome: ^0.2.2
  path: ^1.7.0
  flutter_phosphor_icons: ^0.0.1+3
  image: ^2.1.19
  nanoid: ^0.1.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_gen_runner: ^3.1.1
  flutter_test:
    sdk: flutter
  # flutter_lints: ^1.0.0
  flutter_painter: ^0.0.1


# Flutter gen
flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  assets:
    - assets/images/
    - assets/icons/
